#!/bin/sh
set -euf

# This script is designed to run on the Unix host during the `configure` of
# github.com/ocaml/ocaml. The expectation is that the `make` will run
# inside Wine.

# Support in configure.ac (5.4.1):
#   ocamlsrcdir="$(LC_ALL=C.UTF-8 cygpath -w -- "$ocamlsrcdir")"
#   [prefix="$(LC_ALL=C.UTF-8 cygpath -m "$prefix")"]
usage() {
    echo "Usage: cygpath [-m] [-w] [--] <path>"
    exit 1
}

if [ "$#" -eq 0 ]; then
    usage
fi

optmode=unix
while [ "$#" -gt 0 ]; do
    case "$1" in
        -m|--mixed)
            optmode=mixed
            shift
            ;;
        -w|--windows)
            optmode=windows
            shift
            ;;
        --)
            shift
            break
            ;;
        -*)
            echo "Unknown option: $1"
            usage
            ;;
        *)
            break
            ;;
    esac
done
if [ "$#" -ne 1 ]; then
    usage
fi
input="$1"

case "$optmode" in
    unix)
        winepath --unix "$input"
        ;;
    mixed)
        winepath --windows "$input" | tr "\\" '/'
        ;;
    windows)
        winepath --windows "$input"
        ;;
esac
