name: CommonsBase_Std.Extract.F_TarToZip # we'll build this rule
env:
  LIBRARY_VERSION: 0.1.0        # we'll build this version
on:
  push:              # build on every commit
  workflow_dispatch: # allow manual triggering from GitHub page
  workflow_call:     # allow other workflows to call this workflow

jobs:
    test-windows: # job to build dependencies that only run on Windows
        runs-on: windows-2022
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Checkout # get dksrc/dk0
              uses: actions/checkout@v5
              with: { repository: diskuv/dk, path: dksrc, ref: V2_5 }

            - name: Cache dk data stores and build keys
              uses: actions/cache@v4
              with:
                  # The data stores and build keys are safe to share between Windows, macOS and Linux
                  enableCrossOsArchive: true
                  path: |
                      t/d/val.1
                      t/d/cts.1.*
                      t/c/build.pub
                      t/c/build.sec
                  restore-keys: dk-stores-and-keys             # use latest cache
                  key: dk-stores-and-keys-${{ github.run_id }} # update cache on every run

            - name: Build Windows objects
              shell: pwsh
              # `--trial` helps cross-platform CI caches behave best since cache+data is under the project directory
              run: |
                dksrc/dk0 --trial --print-config
                if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

                dksrc/dk0 --trial -v -nosysinc -I etc/dk/v --trust-local-package CommonsBase_Std -d parsetrace get-object CommonsBase_Std.S7z@25.1.0 -s Release.Windows_x86 -d target/ignore
                if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

            - name: Build and test ${{ github.workflow }} on Windows
              shell: bash
              # `--trial` helps cross-platform CI caches behave best since cache+data is under the project directory
              run: |
                dksrc/dk0.cmd --trial --print-config

                mkdir -p target
                tar cvf target/nothing.tar README.md COPYRIGHT

                dksrc/dk0.cmd --trial -v -nosysinc -I etc/dk/v --trust-local-package CommonsBase_Std post-object CommonsBase_Std.Extract.F_TarToZip@0.1.0 -f target/t2.zip tarfile=$PWD/target/nothing.tar modver=OurTest_Std.T2Zip.Windows_x86_64@0.1.0
                dksrc/dk0.cmd --trial -v -nosysinc -I etc/dk/v --trust-local-package CommonsBase_Std get-object OurTest_Std.T2Zip.Windows_x86_64@0.1.0 -s Release.Agnostic -m ./output.zip -d target/unt2zip
                ls -l target/unt2zip
                test -f target/unt2zip/README.md
                test -f target/unt2zip/COPYRIGHT

                # Windows has a different subrule for .tar.gz/.tar.bz2 than .tar, so test independently
                gzip target/nothing.tar
                dksrc/dk0.cmd --trial -v -nosysinc -I etc/dk/v --trust-local-package CommonsBase_Std post-object CommonsBase_Std.Extract.F_TarToZip@0.1.0 -f target/t2b.zip tarfile=$PWD/target/nothing.tar.gz modver=OurTest_Std.TGz2Zip.Windows_x86_64@0.1.0
                dksrc/dk0.cmd --trial -v -nosysinc -I etc/dk/v --trust-local-package CommonsBase_Std get-object OurTest_Std.TGz2Zip.Windows_x86_64@0.1.0 -s Release.Agnostic -m ./output.zip -d target/untgz2zip
                ls -l target/untgz2zip
                test -f target/untgz2zip/README.md
                test -f target/untgz2zip/COPYRIGHT

            - name: Archive Logs
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                name: windows-logs
                # ex. t/p/456/pild/l/Release.Agnostic/stderr2.log
                path: |
                  t/p/*/*/l/Release.Agnostic/

    test-unix:
        strategy:
          matrix:
            include:
              - os: ubuntu-latest
                abi: Linux_x86_64
              - os: macos-latest
                abi: Darwin_arm64
        runs-on: ${{ matrix.os }}
        needs: test-windows # CommonsBase_Std requires Windows to build the package
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Checkout # get dksrc/dk0
              uses: actions/checkout@v5
              with: { repository: diskuv/dk, path: dksrc, ref: V2_5 }

            - name: Cache dk data stores and build keys
              uses: actions/cache@v4
              with:
                  # The data stores and build keys are safe to share between Windows, macOS and Linux
                  enableCrossOsArchive: true
                  path: |
                      t/d/val.1
                      t/d/cts.1.*
                      t/c/build.pub
                      t/c/build.sec
                  restore-keys: dk-stores-and-keys             # use latest cache
                  key: dk-stores-and-keys-${{ github.run_id }} # update cache on every run

            # We built these on Windows, but we redo build on Linux to verify that dependencies are in
            # tracestore and valuestore, and to extra Linux coreutils.exe for testing.
            - name: Build and test ${{ github.workflow }} on ${{ matrix.os }}
              shell: pwsh
              # `--trial` helps cross-platform CI caches behave best since cache+data is under the project directory
              run: |
                dksrc/dk0 --trial --print-config

                install -d target
                tar cvf target/nothing.tar README.md COPYRIGHT

                dksrc/dk0 --trial -v -nosysinc -I etc/dk/v --trust-local-package CommonsBase_Std post-object CommonsBase_Std.Extract.F_TarToZip@0.1.0 -f target/t2.zip tarfile=$PWD/target/nothing.tar modver=OurTest_Std.T2Zip.${{ matrix.abi }}@0.1.0
                dksrc/dk0 --trial -v -nosysinc -I etc/dk/v --trust-local-package CommonsBase_Std get-object OurTest_Std.T2Zip.${{ matrix.abi }}@0.1.0 -s Release.Agnostic -m ./output.zip -d target/unt2zip
                ls -l target/unt2zip
                test -f target/unt2zip/README.md
                test -f target/unt2zip/COPYRIGHT

            - name: Archive Logs
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                name: unix-logs-${{ matrix.os }}
                # ex. t/p/456/pild/l/Release.Agnostic/stderr2.log
                path: |
                  t/p/*/*/l/Release.Agnostic/
