name: CommonsBase@2.5.x  # we'll build multiple libraries
on:
  push:
    tags:
      - '2.5.*' # build if tag is pushed
    branches:
      - main    # will be translated to `dkdist_branch_version` (prerelease and build metadata can't be used when distributing versions)
  workflow_dispatch: # allow manual triggering from GitHub page
env:
  dkdist_branch_version: 2.5.1 # must have non-zero patch version

jobs:
    # JOB DESIGN:
    #
    # Each job in this workflow is a "package job" that build and distributes a single package.
    # Tags are `VERSION+PACKAGE` (ex. 2.5.202602060017+CommonsBase-Std) where the PACKAGE is
    # the package name with underscores replaced by dashes and periods replaced by double dashes
    # to be valid semver build metadata required by `dk0 import-github-l2 --tag <tag>`.
    # A design alternative to PACKAGE-encoded tags would be to use an input variable for PACKAGE,
    # but that requires the dk developer to go to the GitHub Actions UI and we lose the PACKAGE
    # in `git log`.
    #
    # The +PACKAGE and any other build metadata will be stripped by `diskuv/dk-distribute@v1`.
    # But we wanted PACKAGE to be visible to this GitHub workflow so that each package can be built
    # independently with a self-contained GitHub package job (self-contained == little or no `needs:`),
    # especially since some packages have time-consuming builds. Instead of `needs:` we expect:
    # 1. The developer to do a `dk0 import-github-l2` once a package is built.
    # 2. Each package job in this workflow file to manipulate the etc/dk/i system directory in a
    # `Import and Summarize Packages` step so that only packages that are required (ie. `needs:`) are
    # present in the etc/dk/i directory. For example, the CommonsBase_Build package job should only have
    # the CommonsBase_Std package in its etc/dk/i directory, and especially not have
    # etc/dk/i/CommonsBase_Build.values.json which would conflict with the
    # etc/dk/v/CommonsBase_Build.values.json that should be built.
    #
    # Package independence is also the basic dk design principle of "loose federation
    # of packages" in SPECIFICATION.md; any package job in this workflow file can be moved to a
    # different GitHub repository which is relatively easy to do because we have self-contained
    # GitHub jobs. In particular, packages that are not CommonsBase_* should be moved once the
    # experiment is over.
    #
    # Steps:
    # For the main branch, `Archive` step is save artifacts generated for later debugging.
    # For tags only, `Attest` + `Release` steps are to save attestation and artifacts publicly.

    CommonsBase_Std:
        # tag(2.5.x+CommonsBase-Std) or branch(main)
        if: (github.ref_type == 'tag' && startsWith(github.ref_name, '2.5.') && endsWith(github.ref_name, '+CommonsBase-Std')) || github.ref_name == 'main'

        strategy:
          fail-fast: true
          matrix:
            include:
              - runs-on: windows-2022 # CommonsBase_Std requires Windows to build S7z
                distbase: dist-win32

        runs-on: ${{ matrix.runs-on }}

        permissions:
          contents: write # for action-gh-release
          id-token: write # for actions/attest-build-provenance
          attestations: write # for actions/attest-build-provenance
          artifact-metadata: write # for actions/attest-build-provenance

        # The secrets created by `dksrc/dk0 prepare-version --ci github VERSION`
        # are tied to this environment only.
        environment: dk-distribution
        steps:
            - name: Harden Runner # Optional but recommended
              uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
              with: { egress-policy: audit }
            - name: Checkout project
              uses: actions/checkout@v5

            - name: Import and Summarize Packages # No dependencies so no imports
              shell: bash
              run: |
                ! [ "${{ github.ref_type }}" = "tag" ] || .github/scripts/describe-import-gh-release.sh -m -c "$GITHUB_STEP_SUMMARY" -t '${{ github.ref_name }}' -r '${{ github.repository }}'

            - name: Distribute Modules
              uses: diskuv/dk-distribute@v2
              with:
                  id: ${{ github.ref_type == 'tag' && format('{0}@{1}', github.job, github.ref_name) || format('{0}@{1}', github.job, env.dkdist_branch_version) }}
                  pubkey: ${{ secrets.distribute_2_5_pubkey }}
                  seckey: ${{ secrets.distribute_2_5_seckey }}
                  # dk0=<SOURCE_DIRECTORY>
                  options: -nosysinc -I etc/dk/v --cell "dk0=${{ github.workspace }}"
                  use-cache: true
                  distscript: etc/dk/v/${{ github.job }}/${{ matrix.distbase }}.t
                  experimental-dk-owner: ${{ github.repository_owner}}
                  #   Use MlFront HEAD when CI build is not from a tag
                  experimental-mlfront-ref: ${{ github.ref_type != 'tag' && 'HEAD' }}
                  #   Temporary: use HEAD until MlFront testing is done
                  # experimental-mlfront-ref: HEAD

            - name: Archive Distribution
              if: github.ref_type != 'tag'
              uses: actions/upload-artifact@v4
              with:
                name: dist-CommonsBase_Std
                path: dk-dist/

            - name: Attest
              if: github.ref_type == 'tag'
              id: attest
              uses: actions/attest-build-provenance@v3
              with: { subject-path: dk-dist/* }

            - name: Release ${{ github.job }}
              if: github.ref_type == 'tag'
              uses: softprops/action-gh-release@f38efdea4c5ffe13e9424b0aa2833bee28f1e34c # v2. Oct. 6, 2025
              with: { files: dk-dist/* }

    CommonsBase_Build:
        # tag(2.5.x+CommonsBase-Build) or branch(main)
        if: (github.ref_type == 'tag' && startsWith(github.ref_name, '2.5.') && endsWith(github.ref_name, '+CommonsBase-Build')) || github.ref_name == 'main'

        strategy:
          fail-fast: true
          matrix:
            include:
              - runs-on: ubuntu-24.04
                distbase: dist-any # Linux is cheapest and quickest to boot in Github Actions

        runs-on: ${{ matrix.runs-on }}

        permissions:
          contents: write # for action-gh-release
          id-token: write # for actions/attest-build-provenance
          attestations: write # for actions/attest-build-provenance
          artifact-metadata: write # for actions/attest-build-provenance

        # The secrets created by `dksrc/dk0 prepare-version --ci github VERSION`
        # are tied to this environment only.
        environment: dk-distribution
        steps:
            - name: Harden Runner # Optional but recommended
              uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
              with: { egress-policy: audit }

            - name: Checkout project
              uses: actions/checkout@v5

            - name: Import and Summarize Packages
              shell: bash
              env:
                GH_TOKEN: ${{ github.token }}
                DEPENDENCIES: CommonsBase_Std
              run: |
                find etc/dk/i -mindepth 1 -type f -exec rm -f {} +
                ! [ "${{ github.ref_type }}" = "tag" ] || .github/scripts/describe-import-gh-release.sh -m -c "$GITHUB_STEP_SUMMARY" -t '${{ github.ref_name }}' -r '${{ github.repository }}'
                .github/scripts/import-latest-gh-releases.sh -m -c "$GITHUB_STEP_SUMMARY" -r '${{ github.repository }}' $DEPENDENCIES
                echo delete dependencies ...; for d in $DEPENDENCIES; do rm -vrf etc/dk/v/$d.*.values.json* etc/dk/v/$d/*.values.json*; done
                echo final imports ...; find etc/dk/i -type f

            - name: Distribute Modules
              uses: diskuv/dk-distribute@v2
              with:
                  id: ${{ github.ref_type == 'tag' && format('{0}@{1}', github.job, github.ref_name) || format('{0}@{1}', github.job, env.dkdist_branch_version) }}
                  pubkey: ${{ secrets.distribute_2_5_pubkey }}
                  seckey: ${{ secrets.distribute_2_5_seckey }}
                  options: -nosysinc -I etc/dk/i -I etc/dk/v  --cell "dk0=${{ github.workspace }}" # "Import and Summarize Packages" etc/dk/i rather than default system dependencies dksrc/etc/dk/i
                  use-cache: true
                  distscript: etc/dk/v/${{ github.job }}/${{ matrix.distbase }}.t
                  experimental-dk-owner: ${{ github.repository_owner}}
                  experimental-mlfront-ref: ${{ github.ref_type != 'tag' && 'HEAD' }}

            - name: Archive Distribution
              if: github.ref_type != 'tag'
              uses: actions/upload-artifact@v4
              with:
                name: dist-CommonsBase_Build
                path: dk-dist/

            - name: Attest
              if: github.ref_type == 'tag'
              id: attest
              uses: actions/attest-build-provenance@v3
              with: { subject-path: dk-dist/* }

            - name: Release ${{ github.job }}
              if: github.ref_type == 'tag'
              uses: softprops/action-gh-release@f38efdea4c5ffe13e9424b0aa2833bee28f1e34c # v2. Oct. 6, 2025
              with: { files: dk-dist/* }

    CommonsBase_LLVM:
        # tag(2.5.x+CommonsBase-LLVM) or branch(main)
        if: (github.ref_type == 'tag' && startsWith(github.ref_name, '2.5.') && endsWith(github.ref_name, '+CommonsBase-LLVM')) || github.ref_name == 'main'

        strategy:
          fail-fast: true
          matrix:
            include:
              - runs-on: ubuntu-24.04
                distbase: dist-linux
              - runs-on: windows-2022
                distbase: dist-win32
              - runs-on: macos-latest
                distbase: dist-macos

        runs-on: ${{ matrix.runs-on }}

        permissions:
          contents: write # for action-gh-release
          id-token: write # for actions/attest-build-provenance
          attestations: write # for actions/attest-build-provenance
          artifact-metadata: write # for actions/attest-build-provenance

        # The secrets created by `dksrc/dk0 prepare-version --ci github VERSION`
        # are tied to this environment only.
        environment: dk-distribution
        steps:
            - name: Harden Runner # Optional but recommended
              uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
              with: { egress-policy: audit }

            - name: Checkout project
              uses: actions/checkout@v5

            - name: Import and Summarize Packages
              shell: bash
              env:
                GH_TOKEN: ${{ github.token }}
                DEPENDENCIES: CommonsBase_Std
              run: |
                find etc/dk/i -mindepth 1 -type f -exec rm -f {} +
                ! [ "${{ github.ref_type }}" = "tag" ] || .github/scripts/describe-import-gh-release.sh -m -c "$GITHUB_STEP_SUMMARY" -t '${{ github.ref_name }}' -r '${{ github.repository }}'
                .github/scripts/import-latest-gh-releases.sh -m -c "$GITHUB_STEP_SUMMARY" -r '${{ github.repository }}' $DEPENDENCIES
                echo delete dependencies ...; for d in $DEPENDENCIES; do rm -vrf etc/dk/v/$d.*.values.json* etc/dk/v/$d/*.values.json*; done
                echo final imports ...; find etc/dk/i -type f

            - name: Distribute Modules
              uses: diskuv/dk-distribute@v2
              with:
                  id: ${{ github.ref_type == 'tag' && format('{0}@{1}', github.job, github.ref_name) || format('{0}@{1}', github.job, env.dkdist_branch_version) }}
                  pubkey: ${{ secrets.distribute_2_5_pubkey }}
                  seckey: ${{ secrets.distribute_2_5_seckey }}
                  options: -nosysinc -I etc/dk/i -I etc/dk/v  --cell "dk0=${{ github.workspace }}" # "Import and Summarize Packages" etc/dk/i rather than default system dependencies dksrc/etc/dk/i
                  use-cache: true
                  distscript: etc/dk/v/${{ github.job }}/${{ matrix.distbase }}.t
                  experimental-dk-owner: ${{ github.repository_owner}}
                  experimental-mlfront-ref: ${{ github.ref_type != 'tag' && 'HEAD' }}

            - name: Archive Distribution
              if: github.ref_type != 'tag'
              uses: actions/upload-artifact@v4
              with:
                name: dist-CommonsBase_LLVM
                path: dk-dist/

            - name: Attest
              if: github.ref_type == 'tag'
              id: attest
              uses: actions/attest-build-provenance@v3
              with: { subject-path: dk-dist/* }

            - name: Release ${{ github.job }}
              if: github.ref_type == 'tag'
              uses: softprops/action-gh-release@f38efdea4c5ffe13e9424b0aa2833bee28f1e34c # v2. Oct. 6, 2025
              with: { files: dk-dist/* }

    CommonsBase_GNU:
        # tag(2.5.x+CommonsBase-GNU) or branch(main)
        if: (github.ref_type == 'tag' && startsWith(github.ref_name, '2.5.') && endsWith(github.ref_name, '+CommonsBase-GNU')) || github.ref_name == 'main'

        # runs-on(macOS). This CommonsBase_GNU works on Linux but we are targeting macOS first
        runs-on: macos-latest

        permissions:
          contents: write # for action-gh-release
          id-token: write # for actions/attest-build-provenance
          attestations: write # for actions/attest-build-provenance
          artifact-metadata: write # for actions/attest-build-provenance

        # The secrets created by `dksrc/dk0 prepare-version --ci github VERSION`
        # are tied to this environment only.
        environment: dk-distribution
        steps:
            - name: Harden Runner # Optional but recommended
              uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
              with: { egress-policy: audit }

            - name: Checkout project
              uses: actions/checkout@v5

            - name: Import and Summarize Packages
              shell: bash
              env:
                GH_TOKEN: ${{ github.token }}
                # CommonsBase_LLVM: The LLVM-MinGW toolchain is used to build CommonsBase_GNU.Awk.Win32.LLVM_MinGW@5.3.1
                DEPENDENCIES: CommonsBase_Std CommonsBase_LLVM
              run: |
                find etc/dk/i -mindepth 1 -type f -exec rm -f {} +
                ! [ "${{ github.ref_type }}" = "tag" ] || .github/scripts/describe-import-gh-release.sh -m -c "$GITHUB_STEP_SUMMARY" -t '${{ github.ref_name }}' -r '${{ github.repository }}'
                .github/scripts/import-latest-gh-releases.sh -m -c "$GITHUB_STEP_SUMMARY" -r '${{ github.repository }}' $DEPENDENCIES
                echo delete dependencies ...; for d in $DEPENDENCIES; do rm -vrf etc/dk/v/$d.*.values.json* etc/dk/v/$d/*.values.json*; done
                echo final imports ...; find etc/dk/i -type f

            - name: Distribute Modules
              uses: diskuv/dk-distribute@v1
              with:
                  id: ${{ github.ref_type == 'tag' && format('{0}@{1}', github.job, github.ref_name) || format('{0}@{1}', github.job, env.dkdist_branch_version) }}
                  pubkey: ${{ secrets.distribute_2_5_pubkey }}
                  seckey: ${{ secrets.distribute_2_5_seckey }}
                  options: -nosysinc -I etc/dk/i -I etc/dk/v  --cell "dk0=${{ github.workspace }}" # "Import and Summarize Packages" etc/dk/i rather than default system dependencies dksrc/etc/dk/i
                  # We can only build one operating system in one CI job.
                    # Release.Linux_x86:CommonsBase_GNU.Awk@5.3.1
                    # Release.Linux_x86_64:CommonsBase_GNU.Awk@5.3.1
                    # Release.Linux_arm64:CommonsBase_GNU.Awk@5.3.1

                    # Release.Linux_x86_64.Windows_x86_64:CommonsBase_GNU.Awk.Win32.LLVM_MinGW@5.3.1
                    # Release.Linux_x86_64.Windows_x86:CommonsBase_GNU.Awk.Win32.LLVM_MinGW@5.3.1
                    # Release.Linux_x86_64.Windows_arm64:CommonsBase_GNU.Awk.Win32.LLVM_MinGW@5.3.1
                    # Release.Linux_arm64.Windows_x86_64:CommonsBase_GNU.Awk.Win32.LLVM_MinGW@5.3.1
                    # Release.Linux_arm64.Windows_x86:CommonsBase_GNU.Awk.Win32.LLVM_MinGW@5.3.1
                    # Release.Linux_arm64.Windows_arm64:CommonsBase_GNU.Awk.Win32.LLVM_MinGW@5.3.1

                    # Release.Linux_x86:CommonsBase_GNU.Bison@3.8.2
                    # Release.Linux_x86_64:CommonsBase_GNU.Bison@3.8.2
                    # Release.Linux_arm64:CommonsBase_GNU.Bison@3.8.2

                    # Release.Linux_x86:CommonsBase_GNU.GMP@6.3.0
                    # Release.Linux_x86_64:CommonsBase_GNU.GMP@6.3.0
                    # Release.Linux_arm64:CommonsBase_GNU.GMP@6.3.0

                    # Release.Linux_x86:CommonsBase_GNU.Make@4.4.1
                    # Release.Linux_x86_64:CommonsBase_GNU.Make@4.4.1
                    # Release.Linux_arm64:CommonsBase_GNU.Make@4.4.1

                    # Release.Linux_x86_64.Windows_x86_64:CommonsBase_GNU.Make.Win32.LLVM_MinGW@4.4.1
                    # Release.Linux_x86_64.Windows_x86:CommonsBase_GNU.Make.Win32.LLVM_MinGW@4.4.1
                    # Release.Linux_x86_64.Windows_arm64:CommonsBase_GNU.Make.Win32.LLVM_MinGW@4.4.1
                    # Release.Linux_arm64.Windows_x86_64:CommonsBase_GNU.Make.Win32.LLVM_MinGW@4.4.1
                    # Release.Linux_arm64.Windows_x86:CommonsBase_GNU.Make.Win32.LLVM_MinGW@4.4.1
                    # Release.Linux_arm64.Windows_arm64:CommonsBase_GNU.Make.Win32.LLVM_MinGW@4.4.1

                    # Release.Linux_x86:CommonsBase_GNU.Nettle@3.10.2
                    # Release.Linux_x86_64:CommonsBase_GNU.Nettle@3.10.2
                    # Release.Linux_arm64:CommonsBase_GNU.Nettle@3.10.2

                    # Release.Linux_x86:CommonsBase_GNU.TLS@3.8.12
                    # Release.Linux_x86_64:CommonsBase_GNU.TLS@3.8.12
                    # Release.Linux_arm64:CommonsBase_GNU.TLS@3.8.12

                  objects: |
                    Release.Windows_x86:CommonsBase_GNU.Toolchain.W64dev@2.5.0
                    Release.Windows_x86_64:CommonsBase_GNU.Toolchain.W64dev@2.5.0

                    Release.Darwin_arm64:CommonsBase_GNU.Nettle@3.10.2
                    Release.Darwin_x86_64:CommonsBase_GNU.Nettle@3.10.2

                    Release.Darwin_arm64:CommonsBase_GNU.GMP@6.3.0
                    Release.Darwin_x86_64:CommonsBase_GNU.GMP@6.3.0

                    Release.Darwin_arm64:CommonsBase_GNU.TLS@3.8.12
                    Release.Darwin_x86_64:CommonsBase_GNU.TLS@3.8.12

                    Release.Darwin_arm64:CommonsBase_GNU.Awk@5.3.1
                    Release.Darwin_x86_64:CommonsBase_GNU.Awk@5.3.1

                    Release.Darwin_x86_64.Windows_x86_64:CommonsBase_GNU.Awk.Win32.LLVM_MinGW@5.3.1
                    Release.Darwin_x86_64.Windows_x86:CommonsBase_GNU.Awk.Win32.LLVM_MinGW@5.3.1
                    Release.Darwin_x86_64.Windows_arm64:CommonsBase_GNU.Awk.Win32.LLVM_MinGW@5.3.1
                    Release.Darwin_arm64.Windows_x86_64:CommonsBase_GNU.Awk.Win32.LLVM_MinGW@5.3.1
                    Release.Darwin_arm64.Windows_x86:CommonsBase_GNU.Awk.Win32.LLVM_MinGW@5.3.1
                    Release.Darwin_arm64.Windows_arm64:CommonsBase_GNU.Awk.Win32.LLVM_MinGW@5.3.1

                    Release.Darwin_arm64:CommonsBase_GNU.Bison@3.8.2
                    Release.Darwin_x86_64:CommonsBase_GNU.Bison@3.8.2

                    Release.Darwin_arm64:CommonsBase_GNU.Make@4.4.1
                    Release.Darwin_x86_64:CommonsBase_GNU.Make@4.4.1

                    Release.Darwin_x86_64.Windows_x86_64:CommonsBase_GNU.Make.Win32.LLVM_MinGW@4.4.1
                    Release.Darwin_x86_64.Windows_x86:CommonsBase_GNU.Make.Win32.LLVM_MinGW@4.4.1
                    Release.Darwin_x86_64.Windows_arm64:CommonsBase_GNU.Make.Win32.LLVM_MinGW@4.4.1
                    Release.Darwin_arm64.Windows_x86_64:CommonsBase_GNU.Make.Win32.LLVM_MinGW@4.4.1
                    Release.Darwin_arm64.Windows_x86:CommonsBase_GNU.Make.Win32.LLVM_MinGW@4.4.1
                    Release.Darwin_arm64.Windows_arm64:CommonsBase_GNU.Make.Win32.LLVM_MinGW@4.4.1

                  use-cache: true
                  experimental-mlfront-ref: ${{ github.ref_type != 'tag' && 'HEAD' }}

            - name: Archive Logs
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                name: logs-CommonsBase_GNU
                # ex. t/p/1412/mio7/l/Release.Darwin_x86_64/stderr1.log
                # ex. t/p/5514/mnu2/f/Release.Darwin_arm64/configure.log
                path: |
                  t/p/*/*/l/*/*
                  t/p/*/*/f/*/*
                  t/p/*/*/o/*/*

            - name: Archive Distribution
              if: github.ref_type != 'tag'
              uses: actions/upload-artifact@v4
              with:
                name: dist-CommonsBase_GNU
                path: dk-dist/

            - name: Attest
              if: github.ref_type == 'tag'
              id: attest
              uses: actions/attest-build-provenance@v3
              with: { subject-path: dk-dist/* }

            - name: Release ${{ github.job }}
              if: github.ref_type == 'tag'
              uses: softprops/action-gh-release@f38efdea4c5ffe13e9424b0aa2833bee28f1e34c # v2. Oct. 6, 2025
              with: { files: dk-dist/* }

    NotMatveevKondratyev_Libinotify:
        # tag(2.5.x+NotMatveevKondratyev-Libinotify) or branch(main)
        if: (github.ref_type == 'tag' && startsWith(github.ref_name, '2.5.') && endsWith(github.ref_name, '+NotMatveevKondratyev-Libinotify')) || github.ref_name == 'main'

        # runs-on(macOS). This CommonsBase_GNU works on Linux but we are targeting macOS first
        runs-on: macos-latest

        permissions:
          contents: write # for action-gh-release
          id-token: write # for actions/attest-build-provenance
          attestations: write # for actions/attest-build-provenance
          artifact-metadata: write # for actions/attest-build-provenance

        # The secrets created by `dksrc/dk0 prepare-version --ci github VERSION`
        # are tied to this environment only.
        environment: dk-distribution
        steps:
            - name: Harden Runner # Optional but recommended
              uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
              with: { egress-policy: audit }

            - name: Checkout project
              uses: actions/checkout@v5

            - name: Import and Summarize Packages
              shell: bash
              env:
                GH_TOKEN: ${{ github.token }}
                DEPENDENCIES: CommonsBase_Std CommonsBase_GNU
              run: |
                find etc/dk/i -mindepth 1 -type f -exec rm -f {} +
                ! [ "${{ github.ref_type }}" = "tag" ] || .github/scripts/describe-import-gh-release.sh -m -c "$GITHUB_STEP_SUMMARY" -t '${{ github.ref_name }}' -r '${{ github.repository }}'
                .github/scripts/import-latest-gh-releases.sh -m -c "$GITHUB_STEP_SUMMARY" -r '${{ github.repository }}' $DEPENDENCIES
                echo delete dependencies ...; for d in $DEPENDENCIES; do rm -vrf etc/dk/v/$d.*.values.json* etc/dk/v/$d/*.values.json*; done
                echo final imports ...; find etc/dk/i -type f

            - name: Distribute Modules
              uses: diskuv/dk-distribute@v1
              with:
                  id: ${{ github.ref_type == 'tag' && format('{0}@{1}', github.job, github.ref_name) || format('{0}@{1}', github.job, env.dkdist_branch_version) }}
                  pubkey: ${{ secrets.distribute_2_5_pubkey }}
                  seckey: ${{ secrets.distribute_2_5_seckey }}
                  options: -nosysinc -I etc/dk/i -I etc/dk/v  --cell "dk0=${{ github.workspace }}" # "Import and Summarize Packages" etc/dk/i rather than default system dependencies dksrc/etc/dk/i
                  # We can only build one operating system in one CI job.
                  objects: |
                    Release.Darwin_arm64:NotMatveevKondratyev_Libinotify.Kqueue@0.20240724.0
                    Release.Darwin_x86_64:NotMatveevKondratyev_Libinotify.Kqueue@0.20240724.0
                  use-cache: true
                  experimental-mlfront-ref: ${{ github.ref_type != 'tag' && 'HEAD' }}

            - name: Archive Distribution
              if: github.ref_type != 'tag'
              uses: actions/upload-artifact@v4
              with:
                name: dist-NotMatveevKondratyev_Libinotify
                path: dk-dist/

            - name: Attest
              if: github.ref_type == 'tag'
              id: attest
              uses: actions/attest-build-provenance@v3
              with: { subject-path: dk-dist/* }

            - name: Release ${{ github.job }}
              if: github.ref_type == 'tag'
              uses: softprops/action-gh-release@f38efdea4c5ffe13e9424b0aa2833bee28f1e34c # v2. Oct. 6, 2025
              with: { files: dk-dist/* }

    NotMitEdu_Kerberos:
        # tag(2.5.x+NotMitEdu-Kerberos) or branch(main)
        if: (github.ref_type == 'tag' && startsWith(github.ref_name, '2.5.') && endsWith(github.ref_name, '+NotMitEdu-Kerberos')) || github.ref_name == 'main'

        # runs-on(macOS). This CommonsBase_GNU works on Linux but we are targeting macOS first
        runs-on: macos-latest

        permissions:
          contents: write # for action-gh-release
          id-token: write # for actions/attest-build-provenance
          attestations: write # for actions/attest-build-provenance
          artifact-metadata: write # for actions/attest-build-provenance

        # The secrets created by `dksrc/dk0 prepare-version --ci github VERSION`
        # are tied to this environment only.
        environment: dk-distribution
        steps:
            - name: Harden Runner # Optional but recommended
              uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
              with: { egress-policy: audit }

            - name: Checkout project
              uses: actions/checkout@v5

            - name: Import and Summarize Packages
              shell: bash
              env:
                GH_TOKEN: ${{ github.token }}
                DEPENDENCIES: CommonsBase_Std CommonsBase_GNU
              run: |
                find etc/dk/i -mindepth 1 -type f -exec rm -f {} +
                ! [ "${{ github.ref_type }}" = "tag" ] || .github/scripts/describe-import-gh-release.sh -m -c "$GITHUB_STEP_SUMMARY" -t '${{ github.ref_name }}' -r '${{ github.repository }}'
                .github/scripts/import-latest-gh-releases.sh -m -c "$GITHUB_STEP_SUMMARY" -r '${{ github.repository }}' $DEPENDENCIES
                echo delete dependencies ...; for d in $DEPENDENCIES; do rm -vrf etc/dk/v/$d.*.values.json* etc/dk/v/$d/*.values.json*; done
                echo final imports ...; find etc/dk/i -type f

            - name: Distribute Modules
              uses: diskuv/dk-distribute@v1
              with:
                  id: ${{ github.ref_type == 'tag' && format('{0}@{1}', github.job, github.ref_name) || format('{0}@{1}', github.job, env.dkdist_branch_version) }}
                  pubkey: ${{ secrets.distribute_2_5_pubkey }}
                  seckey: ${{ secrets.distribute_2_5_seckey }}
                  options: -nosysinc -I etc/dk/i -I etc/dk/v  --cell "dk0=${{ github.workspace }}" # "Import and Summarize Packages" etc/dk/i rather than default system dependencies dksrc/etc/dk/i
                  # We can only build one operating system in one CI job.
                  #  Release.Linux_x86:NotMitEdu_Kerberos.V5@1.22.2
                  #  Release.Linux_x86_64:NotMitEdu_Kerberos.V5@1.22.2
                  #  Release.Linux_arm64:NotMitEdu_Kerberos.V5@1.22.2
                  objects: |
                    Release.Darwin_arm64:NotMitEdu_Kerberos.V5@1.22.2
                    Release.Darwin_x86_64:NotMitEdu_Kerberos.V5@1.22.2
                  use-cache: true
                  experimental-mlfront-ref: ${{ github.ref_type != 'tag' && 'HEAD' }}

            - name: Archive Logs
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                name: logs-NotMitEdu_Kerberos
                # ex. t/p/1412/mio7/l/Release.Darwin_x86_64/stderr1.log
                # ex. t/p/5514/mnu2/f/Release.Darwin_arm64/configure.log
                path: |
                  t/p/*/*/l/*/*
                  t/p/*/*/f/*/*
                  t/p/*/*/o/*/*

            - name: Archive Distribution
              if: github.ref_type != 'tag'
              uses: actions/upload-artifact@v4
              with:
                name: dist-NotMitEdu_Kerberos
                path: dk-dist/

            - name: Attest
              if: github.ref_type == 'tag'
              id: attest
              uses: actions/attest-build-provenance@v3
              with: { subject-path: dk-dist/* }

            - name: Release ${{ github.job }}
              if: github.ref_type == 'tag'
              uses: softprops/action-gh-release@f38efdea4c5ffe13e9424b0aa2833bee28f1e34c # v2. Oct. 6, 2025
              with: { files: dk-dist/* }

    CommonsBase_Win32:
        # tag(2.5.x+CommonsBase-Win32) or branch(main)
        if: (github.ref_type == 'tag' && startsWith(github.ref_name, '2.5.') && endsWith(github.ref_name, '+CommonsBase-Win32')) || github.ref_name == 'main'

        # runs-on(macOS). This CommonsBase_GNU works on Linux but we are targeting macOS first
        runs-on: macos-latest

        permissions:
          contents: write # for action-gh-release
          id-token: write # for actions/attest-build-provenance
          attestations: write # for actions/attest-build-provenance
          artifact-metadata: write # for actions/attest-build-provenance

        # The secrets created by `dksrc/dk0 prepare-version --ci github VERSION`
        # are tied to this environment only.
        environment: dk-distribution
        steps:
            - name: Harden Runner # Optional but recommended
              uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
              with: { egress-policy: audit }

            - name: Checkout project
              uses: actions/checkout@v5

            - name: Import and Summarize Packages
              shell: bash
              env:
                GH_TOKEN: ${{ github.token }}
                DEPENDENCIES: CommonsBase_Std CommonsBase_LLVM CommonsBase_GNU NotMatveevKondratyev_Libinotify NotMitEdu_Kerberos
              run: |
                find etc/dk/i -mindepth 1 -type f -exec rm -f {} +
                ! [ "${{ github.ref_type }}" = "tag" ] || .github/scripts/describe-import-gh-release.sh -m -c "$GITHUB_STEP_SUMMARY" -t '${{ github.ref_name }}' -r '${{ github.repository }}'
                .github/scripts/import-latest-gh-releases.sh -m -c "$GITHUB_STEP_SUMMARY" -r '${{ github.repository }}' $DEPENDENCIES
                echo delete dependencies ...; for d in $DEPENDENCIES; do rm -vrf etc/dk/v/$d.*.values.json* etc/dk/v/$d/*.values.json*; done
                echo final imports ...; find etc/dk/i -type f

            - name: Distribute Modules
              uses: diskuv/dk-distribute@v1
              with:
                  id: ${{ github.ref_type == 'tag' && format('{0}@{1}', github.job, github.ref_name) || format('{0}@{1}', github.job, env.dkdist_branch_version) }}
                  pubkey: ${{ secrets.distribute_2_5_pubkey }}
                  seckey: ${{ secrets.distribute_2_5_seckey }}
                  options: -nosysinc -I etc/dk/i -I etc/dk/v  --cell "dk0=${{ github.workspace }}" # "Import and Summarize Packages" etc/dk/i rather than default system dependencies dksrc/etc/dk/i
                  objects: |
                    Release.Darwin_x86_64:CommonsBase_Win32.Wine@11.2.0
                    Release.Darwin_arm64:CommonsBase_Win32.Wine@11.2.0
                  use-cache: true
                  experimental-mlfront-ref: ${{ github.ref_type != 'tag' && 'HEAD' }}

            - name: Archive Logs
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                name: logs-CommonsBase_Win32
                # ex. t/p/1412/mio7/l/Release.Darwin_x86_64/stderr1.log
                # ex. t/p/5514/mnu2/f/Release.Darwin_arm64/configure.log
                # ex. t/p/7096/rd6x/o/Release.Darwin_arm64/lib/wine/i386-windows/winex11.drv
                path: |
                  t/p/*/*/l/*/*
                  t/p/*/*/f/*/*
                  t/p/*/*/o/*/*

            - name: Archive Distribution
              if: github.ref_type != 'tag'
              uses: actions/upload-artifact@v4
              with:
                name: dist-CommonsBase_Win32
                path: dk-dist/

            - name: Attest
              if: github.ref_type == 'tag'
              id: attest
              uses: actions/attest-build-provenance@v3
              with: { subject-path: dk-dist/* }

            - name: Release ${{ github.job }}
              if: github.ref_type == 'tag'
              uses: softprops/action-gh-release@f38efdea4c5ffe13e9424b0aa2833bee28f1e34c # v2. Oct. 6, 2025
              with: { files: dk-dist/* }

    NotInriaCaml_Std:
        # tag(2.5.x+NotInriaCaml-Std) or branch(main)
        if: (github.ref_type == 'tag' && startsWith(github.ref_name, '2.5.') && endsWith(github.ref_name, '+NotInriaCaml-Std')) || github.ref_name == 'main'

        # runs-on(macOS). This CommonsBase_GNU works on Linux but we are targeting macOS first
        runs-on: macos-latest

        permissions:
          contents: write # for action-gh-release
          id-token: write # for actions/attest-build-provenance
          attestations: write # for actions/attest-build-provenance
          artifact-metadata: write # for actions/attest-build-provenance

        # The secrets created by `dksrc/dk0 prepare-version --ci github VERSION`
        # are tied to this environment only.
        environment: dk-distribution
        steps:
            - name: Harden Runner # Optional but recommended
              uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
              with: { egress-policy: audit }

            - name: Checkout project
              uses: actions/checkout@v5

            - name: Import and Summarize Packages
              shell: bash
              env:
                GH_TOKEN: ${{ github.token }}
                DEPENDENCIES: CommonsBase_Std CommonsBase_LLVM CommonsBase_GNU NotMatveevKondratyev_Libinotify NotMitEdu_Kerberos CommonsBase_Win32
              run: |
                find etc/dk/i -mindepth 1 -type f -exec rm -f {} +
                ! [ "${{ github.ref_type }}" = "tag" ] || .github/scripts/describe-import-gh-release.sh -m -c "$GITHUB_STEP_SUMMARY" -t '${{ github.ref_name }}' -r '${{ github.repository }}'
                .github/scripts/import-latest-gh-releases.sh -m -c "$GITHUB_STEP_SUMMARY" -r '${{ github.repository }}' $DEPENDENCIES
                echo delete dependencies ...; for d in $DEPENDENCIES; do rm -vrf etc/dk/v/$d.*.values.json* etc/dk/v/$d/*.values.json*; done
                echo final imports ...; find etc/dk/i -type f

            - name: Distribute Modules
              uses: diskuv/dk-distribute@v1
              with:
                  id: ${{ github.ref_type == 'tag' && format('{0}@{1}', github.job, github.ref_name) || format('{0}@{1}', github.job, env.dkdist_branch_version) }}
                  pubkey: ${{ secrets.distribute_2_5_pubkey }}
                  seckey: ${{ secrets.distribute_2_5_seckey }}
                  options: -nosysinc -I etc/dk/i -I etc/dk/v  --cell "dk0=${{ github.workspace }}" # "Import and Summarize Packages" etc/dk/i rather than default system dependencies dksrc/etc/dk/i
                  # One object takes at least 1.5 hours.
                    # Release.Darwin_arm64.Windows_x86_64:NotInriaCaml_Std.Toolchain.W64devkit@5.4.1
                  objects: |
                    Release.Darwin_x86_64.Windows_x86_64:NotInriaCaml_Std.Toolchain.W64devkit@5.4.1
                  scripts: |
                    NotInriaCaml_Std.Wenv@0.1.0
                  use-cache: true
                  experimental-mlfront-ref: ${{ github.ref_type != 'tag' && 'HEAD' }}

            - name: Archive Logs
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                name: logs-NotInriaCaml_Std
                # ex. t/p/1412/mio7/l/Release.Darwin_x86_64/stderr1.log
                # ex. t/p/5514/mnu2/f/Release.Darwin_arm64/configure.log
                path: |
                  t/p/*/*/l/*/*
                  t/p/*/*/f/*/*
                  t/p/*/*/o/*/*

            - name: Archive Distribution
              if: github.ref_type != 'tag'
              uses: actions/upload-artifact@v4
              with:
                name: dist-NotInriaCaml_Std
                path: dk-dist/

            - name: Attest
              if: github.ref_type == 'tag'
              id: attest
              uses: actions/attest-build-provenance@v3
              with: { subject-path: dk-dist/* }

            - name: Release ${{ github.job }}
              if: github.ref_type == 'tag'
              uses: softprops/action-gh-release@f38efdea4c5ffe13e9424b0aa2833bee28f1e34c # v2. Oct. 6, 2025
              with: { files: dk-dist/* }

    NotGoogleDev_OR:
        # tag(2.5.x+NotGoogleDev-OR) or branch(main)
        if: (github.ref_type == 'tag' && startsWith(github.ref_name, '2.5.') && endsWith(github.ref_name, '+NotGoogleDev-OR')) || github.ref_name == 'main'

        # runs-on(anything). Linux is cheapest and quickest to boot in Github Actions
        runs-on: ubuntu-24.04

        permissions:
          contents: write # for action-gh-release
          id-token: write # for actions/attest-build-provenance
          attestations: write # for actions/attest-build-provenance
          artifact-metadata: write # for actions/attest-build-provenance

        # The secrets created by `dksrc/dk0 prepare-version --ci github VERSION`
        # are tied to this environment only.
        environment: dk-distribution
        steps:
            - name: Harden Runner # Optional but recommended
              uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
              with: { egress-policy: audit }

            - name: Checkout project
              uses: actions/checkout@v5

            - name: Import and Summarize Packages
              shell: bash
              env:
                GH_TOKEN: ${{ github.token }}
                DEPENDENCIES: CommonsBase_Std CommonsBase_Build
              run: |
                find etc/dk/i -mindepth 1 -type f -exec rm -f {} +
                ! [ "${{ github.ref_type }}" = "tag" ] || .github/scripts/describe-import-gh-release.sh -m -c "$GITHUB_STEP_SUMMARY" -t '${{ github.ref_name }}' -r '${{ github.repository }}'
                .github/scripts/import-latest-gh-releases.sh -m -c "$GITHUB_STEP_SUMMARY" -r '${{ github.repository }}' $DEPENDENCIES
                echo delete dependencies ...; for d in $DEPENDENCIES; do rm -vrf etc/dk/v/$d.*.values.json* etc/dk/v/$d/*.values.json*; done
                echo final imports ...; find etc/dk/i -type f

            - name: Distribute Modules
              uses: diskuv/dk-distribute@v1
              with:
                  id: ${{ github.ref_type == 'tag' && format('{0}@{1}', github.job, github.ref_name) || format('{0}@{1}', github.job, env.dkdist_branch_version) }}
                  pubkey: ${{ secrets.distribute_2_5_pubkey }}
                  seckey: ${{ secrets.distribute_2_5_seckey }}
                  options: -nosysinc -I etc/dk/i -I etc/dk/v  --cell "dk0=${{ github.workspace }}" # "Import and Summarize Packages" etc/dk/i rather than default system dependencies dksrc/etc/dk/i
                  scripts: |
                    NotGoogleDev_OR.Tools@9.15.0
                  use-cache: true
                  #   Use MlFront HEAD when CI build is not from a tag
                  experimental-mlfront-ref: ${{ github.ref_type != 'tag' && 'HEAD' }}
                  #   Temporary: use HEAD until MlFront testing is done
                  # experimental-mlfront-ref: HEAD

            - name: Archive Distribution
              if: github.ref_type != 'tag'
              uses: actions/upload-artifact@v4
              with:
                name: dist-NotGoogleDev_OR
                path: dk-dist/

            - name: Attest
              if: github.ref_type == 'tag'
              id: attest
              uses: actions/attest-build-provenance@v3
              with: { subject-path: dk-dist/* }

            - name: Release ${{ github.job }}
              if: github.ref_type == 'tag'
              uses: softprops/action-gh-release@f38efdea4c5ffe13e9424b0aa2833bee28f1e34c # v2. Oct. 6, 2025
              with: { files: dk-dist/* }

    NotInriaParkas_Caml:
        # tag(2.5.x+NotInriaParkas-Caml) or branch(main)
        if: (github.ref_type == 'tag' && startsWith(github.ref_name, '2.5.') && endsWith(github.ref_name, '+NotInriaParkas-Caml')) || github.ref_name == 'main'

        # runs-on(macOS). This NotInriaParkas_Caml package has (so far) been developed only for macOS
        runs-on: macos-latest

        permissions:
          contents: write # for action-gh-release
          id-token: write # for actions/attest-build-provenance
          attestations: write # for actions/attest-build-provenance
          artifact-metadata: write # for actions/attest-build-provenance

        # The secrets created by `dksrc/dk0 prepare-version --ci github VERSION`
        # are tied to this environment only.
        environment: dk-distribution
        steps:
            - name: Harden Runner # Optional but recommended
              uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
              with: { egress-policy: audit }

            - name: Checkout project
              uses: actions/checkout@v5

            - name: Import and Summarize Packages
              shell: bash
              env:
                GH_TOKEN: ${{ github.token }}
                DEPENDENCIES: CommonsBase_Std CommonsBase_Build NotGoogleDev_OR
              run: |
                find etc/dk/i -mindepth 1 -type f -exec rm -f {} +
                ! [ "${{ github.ref_type }}" = "tag" ] || .github/scripts/describe-import-gh-release.sh -m -c "$GITHUB_STEP_SUMMARY" -t '${{ github.ref_name }}' -r '${{ github.repository }}'
                .github/scripts/import-latest-gh-releases.sh -m -c "$GITHUB_STEP_SUMMARY" -r '${{ github.repository }}' $DEPENDENCIES
                echo delete dependencies ...; for d in $DEPENDENCIES; do rm -vrf etc/dk/v/$d.*.values.json* etc/dk/v/$d/*.values.json*; done
                echo final imports ...; find etc/dk/i -type f

            - name: Distribute Modules
              uses: diskuv/dk-distribute@v1
              with:
                  id: ${{ github.ref_type == 'tag' && format('{0}@{1}', github.job, github.ref_name) || format('{0}@{1}', github.job, env.dkdist_branch_version) }}
                  pubkey: ${{ secrets.distribute_2_5_pubkey }}
                  seckey: ${{ secrets.distribute_2_5_seckey }}
                  options: -d parsetrace -d import -nosysinc -I etc/dk/i -I etc/dk/v --cell "dk0=${{ github.workspace }}" # "Import and Summarize Packages" etc/dk/i rather than default system dependencies dksrc/etc/dk/i
                  # TODO: we have a gremlin ... perhaps cached AST ... with SLOT.Release.request translated into Release.Darwin_arm64 even
                  #       though the request is Release.Darwin_x86_64.
                  #       attempt 1: fix to SLOT.request (pending).
                  #       attempt 2: clear ASTs from cache (and then `t/c` entirely).
                  #       mitigation 3: separate job to macos-15-intel (bonus: may be faster than Rosetta emulation)
                  #  Release.Darwin_x86_64:NotInriaParkas_Caml.ORTools@9.15.0
                  objects: |
                    Release.Darwin_arm64:NotInriaParkas_Caml.ORTools@9.15.0
                  use-cache: true
                  #   Use MlFront HEAD when CI build is not from a tag
                  # experimental-mlfront-ref: ${{ github.ref_type != 'tag' && 'HEAD' }}
                  #   Temporary: use HEAD until MlFront testing is done
                  experimental-mlfront-ref: HEAD

            - name: Archive Logs
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                name: logs-NotInriaParkas_Caml
                # ex. t/p/1412/mio7/l/Release.Darwin_x86_64/stderr1.log
                # ex. t/p/5514/mnu2/f/Release.Darwin_arm64/configure.log
                path: |
                  t/p/*/*/l/*/*
                  t/p/*/*/f/*/*
                  t/p/*/*/o/*/*

            - name: Archive Distribution
              if: github.ref_type != 'tag'
              uses: actions/upload-artifact@v4
              with:
                name: dist-NotInriaParkas_Caml
                path: dk-dist/

            - name: Attest
              if: github.ref_type == 'tag'
              id: attest
              uses: actions/attest-build-provenance@v3
              with: { subject-path: dk-dist/* }

            - name: Release ${{ github.job }}
              if: github.ref_type == 'tag'
              uses: softprops/action-gh-release@f38efdea4c5ffe13e9424b0aa2833bee28f1e34c # v2. Oct. 6, 2025
              with: { files: dk-dist/* }
